Perform basic operations on matrices (like addition, subtraction, multiplication) and display
specific rows or columns of the matrix.

In [ ]:
import numpy as np

In [ ]:
mat1 = np.array([1,2,3,4,5,6])
mat2 = np.array([10,20,30,40,50,60])

In [ ]:
#sum the matrix
summed = mat1+mat2

In [ ]:
summed

array([11, 22, 33, 44, 55, 66])

In [ ]:
#subtract the matrix
sub = mat2-mat1

In [ ]:
sub

array([ 9, 18, 27, 36, 45, 54])

In [ ]:
#multiplying the matrix
multi = mat1*mat2

In [ ]:
multi

array([ 10,  40,  90, 160, 250, 360])